FROM golang:1.7-alpine
MAINTAINER Sergey Vasilenko <svasilenko@mirantis.com>

ENV GOPATH /go

RUN apk update && apk add git make \
  && mkdir -p "$GOPATH/src/" "$GOPATH/bin" && chmod -R 777 "$GOPATH" \
  && mkdir -p /go/src/github.com/mickep76/etcdtool

# Copy in the filesystem - this contains confd, bird configs
COPY root-builder/ /

WORKDIR /