#!/bin/sh
exec 2>&1
#sed "s/HOSTNAME/$HOSTNAME/" /etc/confd/templates/bird.toml.template > /etc/confd/conf.d/bird.toml
ETCD_NODE=${ETCD_ENDPOINTS:=${ETCD_SCHEME:=http}://${ETCD_AUTHORITY}}
ETCD_ENDPOINTS_CONFD=`echo "-node=$ETCD_NODE" | sed -e 's/,/ -node=/'`

LOCAL_IPV4=$(ip -4 -o addr show | grep -v ': lo ' | awk '{print $4}' | awk -F'/' '{print $1}')

ETCD_IPV4=${ETCD_IPV4:=${LOCAL_IPV4}}
ETCD_CLUSTER_NAME=${ETCD_CLUSTER_NAME:=etcd0}
ETCD_LISTEN_CLIENT_URLS=${ETCD_LISTEN_CLIENT_URLS:=http://0.0.0.0:2379,http://0.0.0.0:4001}
ETCD_LISTEN_PEER_URLS=${ETCD_LISTEN_PEER_URLS:=http://0.0.0.0:2380}
ETCD_ADVERTISE_CLIENT_URLS=${ETCD_ADVERTISE_CLIENT_URLS:=http://${ETCD_IPV4}:2379,http://${ETCD_IPV4}:4001}

exec etcd -name $ETCD_CLUSTER_NAME \
        -listen-client-urls $ETCD_LISTEN_CLIENT_URLS \
        -listen-peer-urls $ETCD_LISTEN_PEER_URLS \
        -advertise-client-urls $ETCD_ADVERTISE_CLIENT_URLS